// Types Catalogo
export const GET_CATALOGO_SUCCESS = 'GET_CATALOGO_SUCCESS';
export const GET_CATALOGO_REJECTED = 'GET_CATALOGO_REJECTED';
export const GET_CATALOGO_PENDING = 'GET_CATALOGO_PENDING';

export const GET_ID_CATALOGO_SUCCESS = 'GET_ID_CATALOGO_SUCCESS';
export const GET_ID_CATALOGO_REJECTED = 'GET_ID_CATALOGO_REJECTED';
export const GET_ID_CATALOGO_PENDING = 'GET_ID_CATALOGO_PENDING';

export const DELETE_CATALOGO_SUCCESS = 'DELETE_CATALOGO_SUCCESS';
export const DELETE_CATALOGO_REJECTED = 'DELETE_CATALOGO_REJECTED';
export const DELETE_CATALOGO_PENDING = 'DELETE_CATALOGO_PENDING';

export const UPDATE_CATALOGO_SUCCESS = 'UPDATE_CATALOGO_SUCCESS';
export const UPDATE_CATALOGO_REJECTED = 'UPDATE_CATALOGO_REJECTED';
export const UPDATE_CATALOGO_PENDING = 'UPDATE_CATALOGO_PENDING';

export const CREATE_CATALOGO_SUCCESS = 'CREATE_CATALOGO_SUCCESS';
export const CREATE_CATALOGO_REJECTED = 'CREATE_CATALOGO_REJECTED';
export const CREATE_CATALOGO_PENDING = 'CREATE_CATALOGO_PENDING';


// Types Auth
export const POST_USER = 'POST_USER_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';
export const POST_USER_PENDING = 'POST_USER_PENDING';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED';
export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

