// Types Iron Llegada
export const GET_IRONLLEGADA_SUCCESS = 'GET_IRONLLEGADA_SUCCESS';
export const GET_IRONLLEGADA_REJECTED = 'GET_IRONLLEGADA_REJECTED';
export const GET_IRONLLEGADA_PENDING = 'GET_IRONLLEGADA_PENDING';

export const GET_ID_IRONLLEGADA_SUCCESS = 'GET_ID_IRONLLEGADA_SUCCESS';
export const GET_ID_IRONLLEGADA_REJECTED = 'GET_ID_IRONLLEGADA_REJECTED';
export const GET_ID_IRONLLEGADA_PENDING = 'GET_ID_IRONLLEGADA_PENDING';

export const DELETE_IRONLLEGADA_SUCCESS = 'DELETE_IRONLLEGADA_SUCCESS';
export const DELETE_IRONLLEGADA_REJECTED = 'DELETE_IRONLLEGADA_REJECTED';
export const DELETE_IRONLLEGADA_PENDING = 'DELETE_IRONLLEGADA_PENDING';

export const UPDATE_IRONLLEGADA_SUCCESS = 'UPDATE_IRONLLEGADA_SUCCESS';
export const UPDATE_IRONLLEGADA_REJECTED = 'UPDATE_IRONLLEGADA_REJECTED';
export const UPDATE_IRONLLEGADA_PENDING = 'UPDATE_IRONLLEGADA_PENDING';
export const UPDATE_GET_IRONLLEGADA = 'UPDATE_GET_IRONLLEGADA';

export const CREATE_IRONLLEGADA_SUCCESS = 'CREATE_IRONLLEGADA_SUCCESS';
export const CREATE_IRONLLEGADA_REJECTED = 'CREATE_IRONLLEGADA_REJECTED';
export const CREATE_IRONLLEGADA_PENDING = 'CREATE_IRONLLEGADA_PENDING';


// Types Auth
export const POST_USER = 'POST_USER_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';
export const POST_USER_PENDING = 'POST_USER_PENDING';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED';
export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

