export const GET_CATALOGO = 'GET_CATALOGO';
export const GET_CATALOGO_SUCCESS = 'GET_CATALOGO_SUCCESS';
export const GET_CATALOGO_REJECTED = 'GET_CATALOGO_REJECTED';
export const GET_CATALOGO_PENDING = 'GET_CATALOGO_PENDING';


export const POST_USER = 'POST_USER_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';
export const POST_USER_PENDING = 'POST_USER_PENDING';

